name: v2rayng
description: A V2Ray client for Android and iOS
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  provider: ^6.0.5
  
  # 网络请求
  dio: ^5.1.2
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  
  # 依赖注入
  get_it: ^7.6.0
  
  # 工具类
  uuid: ^3.0.7
  path_provider: ^2.0.15
  flutter_svg: ^2.0.5
  intl: ^0.19.0
  
  # UI组件
  cupertino_icons: ^1.0.5
  flutter_spinkit: ^5.2.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.65.0
  
  # 平台通道
  flutter_background_service: ^2.4.6
  
  # 事件总线
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700